### ISSUE TITLE
Maintainer resigned

### ISSUE THREAD

**Issue by ghost** [reposilite-playground/reposilite-aur#11]
@dzikoysk Yesterday I received an email from @MouettE-SC that he is leaving the AUR package for me to maintain and will be moving on.

I am now the maintainer (I am happy to add you as a co-maintainer if you wish, I need an AUR username if you do), you will need to revoke repository rights for security, no point keeping permissions which won't be used any longer.

@MouettE-SC Thanks for all the help, and for writing the initial `PKGBUILD`, I will continue maintaining this package :)

Have a good day,
Polarian

**Comment by dzikoysk** [comment]
Thanks @MouettE-SC for your work! 

I'm fine if you'll still keep these rights, because I'm simply not in a position to maintain that distribution channel for now.

**Comment by ghost** [comment]
@dzikoysk I am still here to maintain the package :)

**Comment by dzikoysk** [comment]
I'm glad to hear that, thanks for your continuous support 💜

**Comment by ghost** [comment]
No problem :)

**Comment by ghost** [comment]
Closing as solved months ago
