### ISSUE TITLE
Building fails due to java-environment=18

### ISSUE THREAD

**Issue by bp-alex** [reposilite-playground/reposilite-aur#12]
The PKGBUILD requires `java-environment=18` but this is no longer available in the repositories, resulting in issues when building on a clean install (eg GitHub Actions build helpers). Only OpenJDK 8, 11, 17 and 20 are presently available (according to `pacman -Ss` as well as https://wiki.archlinux.org/title/Java).

**Comment by ghost** [comment]
@benalexau Sorry for the late response, I had taken a break from Arch for a month or so, also I did not get a notification of this issue being open, I will have to check my notification settings now, sorry about that.

I am aware that Java 18 was removed from the Official Repository, but for stability reasons, and also for better reproducibility, we are using the same version of Java that reposilite uses in its Github actions for compiling the project. I know it is a little bit of a pain however I believe it is still worth the hassle, if reposilite updates their build to a later version of Java we will follow suit here.

If you want to make it easier to install, I have the latest version of Java 18 built within [PolarRepo](https://mirrors.polarian.dev/archlinux), along with the built reposilite package for faster install (and easier updates via pacman -Syu), you can also fetch the build from github too, see [releases](https://github.com/reposilite-playground/reposilite-aur/releases).

Hope this helps,
Polarian

**Comment by bp-alex** [comment]
Thanks @PolarianDev. I have adopted the PolarRepo as a workaround, although I note that upstream has been testing Java 20 in their GitHub Actions workflow and recently [downgraded](https://github.com/dzikoysk/reposilite/commit/b7ca317798b3bba157346fea4a1d388379d78773) to 19.

I suggest it would be more idiomatic for `PKGBUILD` to use the latest available Java on Arch given it's a rolling distro. I have dozens of Java applications (both internal and third party) and they all work on the latest. Reposilite is a fairly standard Java application from what I've seen (it's not doing low-level `Unsafe` operations etc) so is unlikely to be impacted by a more recent Java version. On the other hand I acknowledge the [documentation](https://reposilite.com/guide/standalone) states Java 11-18 so requiring Java 18 is certainly a reasonable approach (then again GitHub Actions indicates 19 would work).

Anyhow I don't mind either way given the workaround you kindly provide via PolarRepo. Please feel free to close this issue if you prefer.

**Comment by ghost** [comment]
@benalexau Hello and sorry for the late reply.

I have updated reposilite to the latest version (as of posting this, `3.4.7`), and with that I have updated the Java version from Java 18 to Java 19 (as it is the current version used in the github actions, and works just fine). This unfortunately is not in the official repository, however I have compiled it to my repository so I can easily build reposilite.

Any issues let me know, I will close this issue.

Take care,
Polarian

**Comment by ghost** [comment]
See #14 for more information 😄
