### ISSUE TITLE
Tag release commits, provide built package which can be pulled directly from github

### ISSUE THREAD

**Issue by ghost** [reposilite-playground/reposilite-aur#2]
As the name of the issue implies, each release within the file should be tagged, and pushed to github, then a release should be created with the built reposilite package.

This allows for better "official" support, allowing users to download the package directly from the reposilite upstream, just like the official builds within the reposilite github repository.

@dzikoysk Let me know here or the commit I submitted within the PR on the reposilite repository on what you think about this.

Have a nice day,
Polarian

**Comment by ghost** [comment]
I have done the first release, and attached the build to it signed with my GPG key, see the following:

https://github.com/reposilite-playground/reposilite-aur/releases/tag/3.4.0

**Comment by dzikoysk** [comment]
I think it looks nice, I'm happy that you are taking care of this area :)

**Comment by ghost** [comment]
Good to know, I will continue this then, we already build the package in a clean environment to test it before releasing the package, so I may as well upload the build with a signature :)

**Comment by ghost** [comment]
@dzikoysk we got a slight issue:

we have updated the build process, to follow your build scripts a lot more, using java-18 and also nodejs 18.x to ensure no issues are introduced by different node or java versions.

However, jre18 is not in the official repositories, thus users need to install java 19 and execute older bytecode, or use PolarRepo directly which ensures all dependencies exist (we build packages using the repo).

However this should make reposilite builds more reproduceable.

Would you like me to continue releasing the packages, and remind a user to install a JRE which is 18+ in order for it to function? or is that going to be more confusing?

**Comment by ghost** [comment]
After thinking about it, using the latest java version in the arch official repos is good enough, this isn't an issue.

I will continue publishing the builds as they come as releases!

**Comment by dzikoysk** [comment]
Yup, just use latest Java version as Reposilite should work with them by default. I'd even say I'd recommend that over older releases.

**Comment by ghost** [comment]
> Yup, just use latest Java version as Reposilite should work with them by default. I'd even say I'd recommend that over older releases.

OK well then, this is a clear improvement then 👍🏻

**Comment by ghost** [comment]
Onedev failed to update, and has destroyed the data, recover from backup and addition of more measures to prevent this occurring again is going to take some time.

Just a little heads up if anyone tries to view the onedev repository.

**Comment by ghost** [comment]
Keep forgetting to do this :/

**Comment by ghost** [comment]
Ok 3.4.3-1 has been released!

**Comment by ghost** [comment]
@dzikoysk I would like to apologise for being inactive, I had taken a break from Arch Linux and I have yet to update the reposilite package for Arch, it used to be updated almost the same day as the release.

I am currently updating it right now.

**Comment by ghost** [comment]
I have pushed 3.4.5-1 and created release for it: https://github.com/reposilite-playground/reposilite-aur/releases/tag/3.4.5-1

**Comment by dzikoysk** [comment]
Don't worry, you don't have to be available all the time and it's good to have some break from time to time. I'm glad you're here tho & thanks for the release! :)

**Comment by ghost** [comment]
For some reason I have not been getting the notifications from Github, was unaware about the two new versions. I will update the package the latest now.

**Comment by ghost** [comment]
Updated to `3.4.9` \o/

**Comment by dzikoysk** [comment]
Great, thanks :)

**Comment by ghost** [comment]
I did an unpopular decision and migrated to Arch gradle (instead of using gradlew), I am aware this could cause build failures and is not officially supported, but it is more conventional for Arch Linux, and after discussion with others I decided to give it a go. It works fine for now so only time will tell :D

**Comment by ghost** [comment]
New version packaged \o/

**Comment by ghost** [comment]
@dzikoysk I apologise but I will be orphaning the package.

Things have come up, and I am getting heat for holding onto packages which I do not have the energy to maintain.

It has been nice talking with you, and I hope someone else will pick up the package and help out. You are free to remove the permissions to this repository from me.

I will redirect users from [AUR](https://aur.archlinux.org/packages/reposilite) to here so that they can help out.

In January/February I might return, but I can't hold maintainer on a package I am not actively maintaining, so I will need to drop it for the time being.

See you around,
Polarian

**Comment by dzikoysk** [comment]
Thank you for your contribution to our ecosystem! I fully understand why you can feel that way, so I hope you'll find the energy to do stuff you like. Taking a break is really important to avoid any kind of burnout, but remember that you're always welcome here or on our Discord server :)

**Comment by MouettE-SC** [comment]
Hello @dzikoysk . I am (re)-taking over maintaining the reposilite-aur package. I have updated everything to 3.5.6, created a release with the package attached.

I choose a different way of packaging reposilite (I remember discussing it with polarian and we did not agree on that) which to simply repackage the binary jar you officially produce, skipping re-compilation of the package. It's simplier on the packaging side avoiding version issues regarding compilation tools. The build process is completely automated following releases on the official repository.

I will close this for now as it should be fixed. Let me know if you have any comment or questions !

**Comment by dzikoysk** [comment]
Hey @MouettE-SC, it's really nice to see you here again! 

Like I said to Polarian, I don't really mind on how you guys decide to manage this package - as long as you think it fits you, then I'm fine with it. 

Also thanks for your time, and in case of any issues/changes on my side that could make your life easier, just let me know, maybe we can improve some stuff out there :)
