### ISSUE TITLE
Setup Discord integration

### ISSUE THREAD

**Issue by dzikoysk** [reposilite-playground/reposilite-aur#20]
I need to configure a webhook for this repository, so we can receive updates on #github channel. Hopefully, now I won't forget to actually do it.

**Comment by ghost** [comment]
Why do you need a webhook for Discord from this repository, to slap me on the wrist when I forget to bump the package 😉

**Comment by dzikoysk** [comment]
Hah, not really. Mostly for consistency across our repositories, better notifications for me & users :)

**Comment by ghost** [comment]
It was meant to be a joke haha.
