### ISSUE TITLE
[Question] Force latest Java version?

### ISSUE THREAD

**Issue by ghost** [reposilite-playground/reposilite-aur#21]
Hello,

I intentionally asked this on the Arch Linux Mailing List, to see what others thought about the situation, however I received no responses, see [this thread](https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/thread/AN7BTNL72WNUSY4QMTSAPLWEJ7XUF6ZJ/).

So I will ask here, I am mainly curious in the opinion of @dzikoysk on this topic. The latest Java version (I believe its 21) can build reposilite, and it is faster and more memory efficient, so is there any reason not to use latest version?

Take care,
Polarian

**Comment by dzikoysk** [comment]
There were some issues with jdk20 on GitHub CI, so we just use 19. Anyway, it's a good idea to move to 21 tho, because it's LTS version.

**Comment by ghost** [comment]
I will try building the current version with jdk21 and see what happens.

**Comment by dzikoysk** [comment]
For now, we can't move to JDK21 - Gradle & Kotlin DSL are simply not ready for that:

* https://github.com/dzikoysk/reposilite/issues/1960#issuecomment-1775343619

Anyway, JDK20 seems to work, so that's an upgrade over JDK19.

**Comment by ghost** [comment]
I will move the package over to JDK20 when I get a chance, however JDk20 no longer exists in Arch because its not LTS and it is not latest.

I will probably need to yank it from the official repo history and then pull it into the AUR.

**Comment by ghost** [comment]
https://github.com/dzikoysk/reposilite/issues/1959 new release.

`jdk20-openjdk` is needed to be packaged before I can package this, I will speak to a staff member for advice on this due to recent changes.
