### ISSUE TITLE
NPM warning while building [3.4.1]

### ISSUE THREAD

**Issue by ghost** [reposilite-playground/reposilite-aur#7]
The following warning was found when building this version:

```
> Task :reposilite-frontend:npmInstall
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'reposilite-frontend@3.4.1',
npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=9.5.0' },
npm WARN EBADENGINE   current: { node: 'v18.15.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

First up, it seems like the npm version is outdated, but this was pulled directly from arch's repository so I do not know why this is occurring.

**Comment by MouettE-SC** [comment]
Another good reason to switch to a binary based build ;-)

**Comment by ghost** [comment]
@MouettE-SC I am still for source based builds, it also diagnoses more issues than downloading and hoping the binary works 📦

**Comment by ghost** [comment]
You also cant patch binaries, which can be useful if an arch related bug is created, why do you think the official repositories always do source installs?

**Comment by MouettE-SC** [comment]
> You also cant patch binaries, which can be useful if an arch related bug is created, why do you think the official repositories always do source installs?

Most of java packages in the official repositories are binary based. It makes sense given the nature of the java language.

**Comment by ghost** [comment]
@MouettE-SC examples?

and also I would disagree, it depends on which JDK was used to compile the bytecode, there is legitimate reasons to compile it from source, like the ability to patch.

Although we aren't using patching here :P

**Comment by MouettE-SC** [comment]
Here are the one I found:

- [beanshell](https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/beanshell/trunk/PKGBUILD)
- [ditaa](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/ditaa/trunk/PKGBUILD)
- [freecol](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/freecol/trunk/PKGBUILD)
- [geotag](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/geotag/trunk/PKGBUILD)
- [gephi](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/gephi/trunk/PKGBUILD)
- [gpsprune](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/gpsprune/trunk/PKGBUILD)
- [java-avalon-framework](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/java-avalon-framework/trunk/PKGBUILD)
- [java-commons-io](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/java-commons-io/trunk/PKGBUILD)
- [java-commons-logging](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/java-commons-logging/trunk/PKGBUILD)
- [java-hamcrest](https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/java-hamcrest/trunk/PKGBUILD)
- [java-xmlgraphics-commons](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/java-xmlgraphics-commons/trunk/PKGBUILD)
- [jenkins](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/jenkins/trunk/PKGBUILD)
- [jlatexmath](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/jlatexmath/trunk/PKGBUILD)
- [jmol](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/jmol/trunk/PKGBUILD)
- [josm](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/josm/trunk/PKGBUILD)
- [languagetool](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/languagetool/trunk/PKGBUILD)
- [offroad](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/offroad/trunk/PKGBUILD)
- [rhino](https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/rhino/trunk/PKGBUILD)
- [sbt](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/sbt/trunk/PKGBUILD)
- [sdedit](https://raw.githubusercontent.com/archlinux/svntogit-community/packages/sdedit/trunk/PKGBUILD)

That being said, there are also packages built from source. So I guess the only thing we can deduce is that both binary and source based builds are acceptable in arch packages.

I'd like to emphasize the fact that jenkins is a popular binary based package with a lot more complexity than reposilite. They do not seem to fear JDK incompatibility.

**Comment by MouettE-SC** [comment]
> and also I would disagree, it depends on which JDK was used to compile the bytecode, there is legitimate reasons to compile it from source, like the ability to patch.

Backend code is written in Kotlin. Any JDK incompatibility would probably be very hard to identify, let alone to patch (imagine if the problem comes from kotlin libraries). Also problem with JDK versions are much less frequent with modern JDK and very unlikely to happen. In any case we could pin the java-runtime to a LTS version in that case while waiting for upstream to fix the problem (which they'll eventually need to do).

Honestly what's worry me about the source build is not the java part but the frontend part (node+npm) which is much more likely to break on arch with bleeding edge versions (or late versions as is the problem in this issue). That's why a binary build would be for us maintainers much easier.

**Comment by ghost** [comment]
Yes but you are meant to compile it with the latest versions of npm and node.

You got to remember Arch Linux is rolling release, it is meant to be bleeding edge, these issues are to be expected, and it would be unconventional to change it.

If there is an issue, we (me and you) are required to either patch upstream to make it compatible, or ask @dzikoysk to support the bleeding edge features.

Arch TUs do a **LOT** more than just package the software, they do need to patch it to use the latest features, and yes this does cause packages to break, but unfortunately that is just how Arch Linux works.

**Comment by ghost** [comment]
Anyways I did not get this error when building 3.4.3, so I will close this issue!

**Comment by dzikoysk** [comment]
Npm likes to complain, but in each release I'm trying to bump all dependencies to the latest versions anyway, so I guess it should match the way you're distributing this.

**Comment by ghost** [comment]
> Npm likes to complain, but in each release I'm trying to bump all dependencies to the latest versions anyway, so I guess it should match the way you're distributing this.

@dzikoysk that is highly useful, and yes it should. And it is not the way we choose, its literally conventionally how Arch Linux works.

It keeps rolling updates, and any projects which dont keep up are either patched by the package maintainer or dropped completely, that is the major drawback of rolling release.

**Comment by MouettE-SC** [comment]
> Yes but you are meant to compile it with the latest versions of npm and node.
> 
> You got to remember Arch Linux is rolling release, it is meant to be bleeding edge, these issues are to be expected, and it would be unconventional to change it.

In that case we should unpin the java and node version from the PKGBUILD no ?
